//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAR.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_ADDR_OBJ_DIVISION
    {
        public int ID { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public Nullable<int> CHILDID { get; set; }
        public Nullable<int> CHANGEID { get; set; }
    }
}
