//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAR.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_CARPLACES_PARAMS
    {
        public int ID { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<int> CHANGEID { get; set; }
        public Nullable<int> CHANGEIDEND { get; set; }
        public Nullable<short> TYPEID { get; set; }
        public string VALUE { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
    }
}
