//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAR.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_HOUSE_TYPES
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SHORTNAME { get; set; }
        public string DESC { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string ISACTIVE { get; set; }
    }
}
