//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAR.BL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_HOUSES
    {
        public int ID { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public string OBJECTGUID { get; set; }
        public Nullable<int> CHANGEID { get; set; }
        public string HOUSENUM { get; set; }
        public string ADDNUM1 { get; set; }
        public string ADDNUM2 { get; set; }
        public Nullable<short> HOUSETYPE { get; set; }
        public Nullable<short> ADDTYPE1 { get; set; }
        public Nullable<short> ADDTYPE2 { get; set; }
        public Nullable<short> OPERTYPEID { get; set; }
        public Nullable<int> PREVID { get; set; }
        public Nullable<int> NEXTID { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<short> ISACTUAL { get; set; }
        public Nullable<short> ISACTIVE { get; set; }
    }
}
